export enum Permission {
    // System-level permission
    SYSTEM_ALL = 'SYSTEM_ALL',

    // Role management
    ROLE_CREATE = 'ROLE_CREATE',
    ROLE_UPDATE = 'ROLE_UPDATE',
    ROLE_VIEW = 'ROLE_VIEW',

    // User management
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_VIEW = 'USER_VIEW',

    // Section management
    SECTION_CREATE = 'SECTION_CREATE',
    SECTION_UPDATE = 'SECTION_UPDATE',
    SECTION_VIEW = 'SECTION_VIEW',
    SECTION_ASSIGN_WORKER = 'SECTION_ASSIGN_WORKER',
    SECTION_CLOSE = 'SECTION_CLOSE',

    // Section daily report
    SECTION_DAILY_REPORT_CREATE = 'SECTION_DAILY_REPORT_CREATE',
    SECTION_DAILY_REPORT_UPDATE = 'SECTION_DAILY_REPORT_UPDATE',
    SECTION_DAILY_REPORT_VIEW = 'SECTION_DAILY_REPORT_VIEW',

    // Section disease
    SECTION_DISEASE_CREATE = 'SECTION_DISEASE_CREATE',
    SECTION_DISEASE_UPDATE = 'SECTION_DISEASE_UPDATE',
    SECTION_DISEASE_VIEW = 'SECTION_DISEASE_VIEW',

    // Warehouse
    WAREHOUSE_VIEW = 'WAREHOUSE_VIEW',
    WAREHOUSE_IN = 'WAREHOUSE_IN',
    WAREHOUSE_OUT = 'WAREHOUSE_OUT',
    WAREHOUSE_UPDATE = 'WAREHOUSE_UPDATE',

    // Inventory
    INVENTORY_CREATE = 'INVENTORY_CREATE',
    INVENTORY_READ = 'INVENTORY_READ',
    INVENTORY_UPDATE = 'INVENTORY_UPDATE',
    INVENTORY_DELETE = 'INVENTORY_DELETE',
    INVENTORY_APPROVE = 'INVENTORY_APPROVE',

    // Medication
    MEDICATION_READ = 'MEDICATION_READ',
    MEDICATION_CREATE = 'MEDICATION_CREATE',
    MEDICATION_UPDATE = 'MEDICATION_UPDATE',
    MEDICATION_DELETE = 'MEDICATION_DELETE',

    // Disease
    DISEASE_READ = 'DISEASE_READ',
    DISEASE_CREATE = 'DISEASE_CREATE',
    DISEASE_UPDATE = 'DISEASE_UPDATE',
    DISEASE_DELETE = 'DISEASE_DELETE',

    // Attendance
    ATTENDANCE_READ = 'ATTENDANCE_READ',
    ATTENDANCE_CREATE = 'ATTENDANCE_CREATE',
    ATTENDANCE_UPDATE = 'ATTENDANCE_UPDATE',
    ATTENDANCE_DELETE = 'ATTENDANCE_DELETE',
    ATTENDANCE_APPROVE = 'ATTENDANCE_APPROVE',

    // GPS Monitor
    GPS_MONITOR_READ = 'GPS_MONITOR_READ',
    GPS_MONITOR_UPDATE = 'GPS_MONITOR_UPDATE',

    // Reporting
    REPORT_VIEW = 'REPORT_VIEW',
    REPORT_EXPORT = 'REPORT_EXPORT',

    // Dashboard
    DASHBOARD_READ = 'DASHBOARD_READ',
    KPI_READ = 'KPI_READ',

    // New Manager Permissions
    SECTION_DAILY_REPORT_APPROVE = 'SECTION_DAILY_REPORT_APPROVE',
    SECTION_STATUS_UPDATE = 'SECTION_STATUS_UPDATE',
    BATCH_CREATE = 'BATCH_CREATE',
    BATCH_CLOSE = 'BATCH_CLOSE',
}

export interface IAssignedSection {
    _id: string;
    name: string;
}

export interface IUser {
    id: string;
    username: string;
    fullName: string;
    role: {
        id: string;
        name: string;
        permissions: Permission[];
    };
    assignedSections?: IAssignedSection[];
    activeDelegations?: {
        permissions: Permission[];
    }[];
}

export interface LoginResponse {
    token: string;
    user: IUser;
}
